name: ZUCC Auto Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas
          python -m pip install xlrd
          python -m pip install requests
      - name: Auto Check
        run: python main.py
